disabled_rules: # rule identifiers turned on by default to exclude from running
  - colon
  - comma
  - control_statement
  - identifier_name
  - cyclomatic_complexity
  - xctfail_message
  - nesting
  - discouraged_direct_init

excluded:
  - Example
  - ExampleTVOS

allow_zero_lintable_files: false

line_length: 250

type_body_length:
  warning: 300
  error: 800

function_body_length: 150

file_length:
  warning: 500
  error: 1200

type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: 
    - iPhone
    - DB
  allowed_symbols: ["_"]
