// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proto/eventcounter/variation_count.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Bucketeer_Eventcounter_VariationCount {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var variationID: String = String()

  var userCount: Int64 = 0

  var eventCount: Int64 = 0

  var valueSum: Double = 0

  var createdAt: Int64 = 0

  var variationValue: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "bucketeer.eventcounter"

extension Bucketeer_Eventcounter_VariationCount: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".VariationCount"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "variation_id"),
    2: .standard(proto: "user_count"),
    3: .standard(proto: "event_count"),
    4: .standard(proto: "value_sum"),
    5: .standard(proto: "created_at"),
    6: .standard(proto: "variation_value"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.variationID)
      case 2: try decoder.decodeSingularInt64Field(value: &self.userCount)
      case 3: try decoder.decodeSingularInt64Field(value: &self.eventCount)
      case 4: try decoder.decodeSingularDoubleField(value: &self.valueSum)
      case 5: try decoder.decodeSingularInt64Field(value: &self.createdAt)
      case 6: try decoder.decodeSingularStringField(value: &self.variationValue)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.variationID.isEmpty {
      try visitor.visitSingularStringField(value: self.variationID, fieldNumber: 1)
    }
    if self.userCount != 0 {
      try visitor.visitSingularInt64Field(value: self.userCount, fieldNumber: 2)
    }
    if self.eventCount != 0 {
      try visitor.visitSingularInt64Field(value: self.eventCount, fieldNumber: 3)
    }
    if self.valueSum != 0 {
      try visitor.visitSingularDoubleField(value: self.valueSum, fieldNumber: 4)
    }
    if self.createdAt != 0 {
      try visitor.visitSingularInt64Field(value: self.createdAt, fieldNumber: 5)
    }
    if !self.variationValue.isEmpty {
      try visitor.visitSingularStringField(value: self.variationValue, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Bucketeer_Eventcounter_VariationCount, rhs: Bucketeer_Eventcounter_VariationCount) -> Bool {
    if lhs.variationID != rhs.variationID {return false}
    if lhs.userCount != rhs.userCount {return false}
    if lhs.eventCount != rhs.eventCount {return false}
    if lhs.valueSum != rhs.valueSum {return false}
    if lhs.createdAt != rhs.createdAt {return false}
    if lhs.variationValue != rhs.variationValue {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
