// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proto/notification/subscription.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Bucketeer_Notification_Subscription {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: String {
    get {return _storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  var createdAt: Int64 {
    get {return _storage._createdAt}
    set {_uniqueStorage()._createdAt = newValue}
  }

  var updatedAt: Int64 {
    get {return _storage._updatedAt}
    set {_uniqueStorage()._updatedAt = newValue}
  }

  var disabled: Bool {
    get {return _storage._disabled}
    set {_uniqueStorage()._disabled = newValue}
  }

  var sourceTypes: [Bucketeer_Notification_Subscription.SourceType] {
    get {return _storage._sourceTypes}
    set {_uniqueStorage()._sourceTypes = newValue}
  }

  var recipient: Bucketeer_Notification_Recipient {
    get {return _storage._recipient ?? Bucketeer_Notification_Recipient()}
    set {_uniqueStorage()._recipient = newValue}
  }
  /// Returns true if `recipient` has been explicitly set.
  var hasRecipient: Bool {return _storage._recipient != nil}
  /// Clears the value of `recipient`. Subsequent reads from it will return its default value.
  mutating func clearRecipient() {_uniqueStorage()._recipient = nil}

  var name: String {
    get {return _storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum SourceType: SwiftProtobuf.Enum {
    typealias RawValue = Int
    case domainEventFeature // = 0
    case domainEventGoal // = 1
    case domainEventExperiment // = 2
    case domainEventAccount // = 3
    case domainEventApikey // = 4
    case domainEventSegment // = 5
    case domainEventEnvironment // = 6
    case domainEventAdminAccount // = 7
    case domainEventAutoopsRule // = 8
    case domainEventPush // = 9
    case domainEventSubscription // = 10
    case domainEventAdminSubscription // = 11
    case featureStale // = 100
    case UNRECOGNIZED(Int)

    init() {
      self = .domainEventFeature
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .domainEventFeature
      case 1: self = .domainEventGoal
      case 2: self = .domainEventExperiment
      case 3: self = .domainEventAccount
      case 4: self = .domainEventApikey
      case 5: self = .domainEventSegment
      case 6: self = .domainEventEnvironment
      case 7: self = .domainEventAdminAccount
      case 8: self = .domainEventAutoopsRule
      case 9: self = .domainEventPush
      case 10: self = .domainEventSubscription
      case 11: self = .domainEventAdminSubscription
      case 100: self = .featureStale
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .domainEventFeature: return 0
      case .domainEventGoal: return 1
      case .domainEventExperiment: return 2
      case .domainEventAccount: return 3
      case .domainEventApikey: return 4
      case .domainEventSegment: return 5
      case .domainEventEnvironment: return 6
      case .domainEventAdminAccount: return 7
      case .domainEventAutoopsRule: return 8
      case .domainEventPush: return 9
      case .domainEventSubscription: return 10
      case .domainEventAdminSubscription: return 11
      case .featureStale: return 100
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

#if swift(>=4.2)

extension Bucketeer_Notification_Subscription.SourceType: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [Bucketeer_Notification_Subscription.SourceType] = [
    .domainEventFeature,
    .domainEventGoal,
    .domainEventExperiment,
    .domainEventAccount,
    .domainEventApikey,
    .domainEventSegment,
    .domainEventEnvironment,
    .domainEventAdminAccount,
    .domainEventAutoopsRule,
    .domainEventPush,
    .domainEventSubscription,
    .domainEventAdminSubscription,
    .featureStale,
  ]
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "bucketeer.notification"

extension Bucketeer_Notification_Subscription: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Subscription"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .standard(proto: "created_at"),
    3: .standard(proto: "updated_at"),
    4: .same(proto: "disabled"),
    5: .standard(proto: "source_types"),
    6: .same(proto: "recipient"),
    7: .same(proto: "name"),
  ]

  fileprivate class _StorageClass {
    var _id: String = String()
    var _createdAt: Int64 = 0
    var _updatedAt: Int64 = 0
    var _disabled: Bool = false
    var _sourceTypes: [Bucketeer_Notification_Subscription.SourceType] = []
    var _recipient: Bucketeer_Notification_Recipient? = nil
    var _name: String = String()

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _id = source._id
      _createdAt = source._createdAt
      _updatedAt = source._updatedAt
      _disabled = source._disabled
      _sourceTypes = source._sourceTypes
      _recipient = source._recipient
      _name = source._name
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularStringField(value: &_storage._id)
        case 2: try decoder.decodeSingularInt64Field(value: &_storage._createdAt)
        case 3: try decoder.decodeSingularInt64Field(value: &_storage._updatedAt)
        case 4: try decoder.decodeSingularBoolField(value: &_storage._disabled)
        case 5: try decoder.decodeRepeatedEnumField(value: &_storage._sourceTypes)
        case 6: try decoder.decodeSingularMessageField(value: &_storage._recipient)
        case 7: try decoder.decodeSingularStringField(value: &_storage._name)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._id.isEmpty {
        try visitor.visitSingularStringField(value: _storage._id, fieldNumber: 1)
      }
      if _storage._createdAt != 0 {
        try visitor.visitSingularInt64Field(value: _storage._createdAt, fieldNumber: 2)
      }
      if _storage._updatedAt != 0 {
        try visitor.visitSingularInt64Field(value: _storage._updatedAt, fieldNumber: 3)
      }
      if _storage._disabled != false {
        try visitor.visitSingularBoolField(value: _storage._disabled, fieldNumber: 4)
      }
      if !_storage._sourceTypes.isEmpty {
        try visitor.visitPackedEnumField(value: _storage._sourceTypes, fieldNumber: 5)
      }
      if let v = _storage._recipient {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      }
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 7)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Bucketeer_Notification_Subscription, rhs: Bucketeer_Notification_Subscription) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._id != rhs_storage._id {return false}
        if _storage._createdAt != rhs_storage._createdAt {return false}
        if _storage._updatedAt != rhs_storage._updatedAt {return false}
        if _storage._disabled != rhs_storage._disabled {return false}
        if _storage._sourceTypes != rhs_storage._sourceTypes {return false}
        if _storage._recipient != rhs_storage._recipient {return false}
        if _storage._name != rhs_storage._name {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Bucketeer_Notification_Subscription.SourceType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "DOMAIN_EVENT_FEATURE"),
    1: .same(proto: "DOMAIN_EVENT_GOAL"),
    2: .same(proto: "DOMAIN_EVENT_EXPERIMENT"),
    3: .same(proto: "DOMAIN_EVENT_ACCOUNT"),
    4: .same(proto: "DOMAIN_EVENT_APIKEY"),
    5: .same(proto: "DOMAIN_EVENT_SEGMENT"),
    6: .same(proto: "DOMAIN_EVENT_ENVIRONMENT"),
    7: .same(proto: "DOMAIN_EVENT_ADMIN_ACCOUNT"),
    8: .same(proto: "DOMAIN_EVENT_AUTOOPS_RULE"),
    9: .same(proto: "DOMAIN_EVENT_PUSH"),
    10: .same(proto: "DOMAIN_EVENT_SUBSCRIPTION"),
    11: .same(proto: "DOMAIN_EVENT_ADMIN_SUBSCRIPTION"),
    100: .same(proto: "FEATURE_STALE"),
  ]
}
