lane :setup do
  ["BucketeerTests", "Example", "ExampleTVOS", "Bucketeer2Tests"].each do |dir|
    sh "cp ./environment.plist ../#{dir}/environment.plist"
    ["apiURL", "sdkKey"].each do |key|
      set_info_plist_value(
        path: "./#{dir}/environment.plist", 
        key: key,
        value: ENV[key],
        output_file_name: "./#{dir}/environment.plist"
      )
    end
  end
end