// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proto/feature/feature_last_used_info.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Bucketeer_Feature_FeatureLastUsedInfo {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var featureID: String = String()

  var version: Int32 = 0

  var lastUsedAt: Int64 = 0

  var createdAt: Int64 = 0

  var clientOldestVersion: String = String()

  var clientLatestVersion: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "bucketeer.feature"

extension Bucketeer_Feature_FeatureLastUsedInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FeatureLastUsedInfo"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "feature_id"),
    2: .same(proto: "version"),
    3: .standard(proto: "last_used_at"),
    4: .standard(proto: "created_at"),
    5: .standard(proto: "client_oldest_version"),
    6: .standard(proto: "client_latest_version"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.featureID)
      case 2: try decoder.decodeSingularInt32Field(value: &self.version)
      case 3: try decoder.decodeSingularInt64Field(value: &self.lastUsedAt)
      case 4: try decoder.decodeSingularInt64Field(value: &self.createdAt)
      case 5: try decoder.decodeSingularStringField(value: &self.clientOldestVersion)
      case 6: try decoder.decodeSingularStringField(value: &self.clientLatestVersion)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.featureID.isEmpty {
      try visitor.visitSingularStringField(value: self.featureID, fieldNumber: 1)
    }
    if self.version != 0 {
      try visitor.visitSingularInt32Field(value: self.version, fieldNumber: 2)
    }
    if self.lastUsedAt != 0 {
      try visitor.visitSingularInt64Field(value: self.lastUsedAt, fieldNumber: 3)
    }
    if self.createdAt != 0 {
      try visitor.visitSingularInt64Field(value: self.createdAt, fieldNumber: 4)
    }
    if !self.clientOldestVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.clientOldestVersion, fieldNumber: 5)
    }
    if !self.clientLatestVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.clientLatestVersion, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Bucketeer_Feature_FeatureLastUsedInfo, rhs: Bucketeer_Feature_FeatureLastUsedInfo) -> Bool {
    if lhs.featureID != rhs.featureID {return false}
    if lhs.version != rhs.version {return false}
    if lhs.lastUsedAt != rhs.lastUsedAt {return false}
    if lhs.createdAt != rhs.createdAt {return false}
    if lhs.clientOldestVersion != rhs.clientOldestVersion {return false}
    if lhs.clientLatestVersion != rhs.clientLatestVersion {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
