//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: proto/feature/service.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate Bucketeer_Feature_FeatureServiceClient, then call methods of this protocol to make API calls.
internal protocol Bucketeer_Feature_FeatureServiceClientProtocol: GRPCClient {
  func searchFeatures(
    _ request: Bucketeer_Feature_SearchFeaturesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_SearchFeaturesRequest, Bucketeer_Feature_SearchFeaturesResponse>

  func getFeature(
    _ request: Bucketeer_Feature_GetFeatureRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_GetFeatureRequest, Bucketeer_Feature_GetFeatureResponse>

  func getFeatures(
    _ request: Bucketeer_Feature_GetFeaturesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_GetFeaturesRequest, Bucketeer_Feature_GetFeaturesResponse>

  func listFeatures(
    _ request: Bucketeer_Feature_ListFeaturesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_ListFeaturesRequest, Bucketeer_Feature_ListFeaturesResponse>

  func listEnabledFeatures(
    _ request: Bucketeer_Feature_ListEnabledFeaturesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_ListEnabledFeaturesRequest, Bucketeer_Feature_ListEnabledFeaturesResponse>

  func createFeature(
    _ request: Bucketeer_Feature_CreateFeatureRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_CreateFeatureRequest, Bucketeer_Feature_CreateFeatureResponse>

  func enableFeature(
    _ request: Bucketeer_Feature_EnableFeatureRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_EnableFeatureRequest, Bucketeer_Feature_EnableFeatureResponse>

  func disableFeature(
    _ request: Bucketeer_Feature_DisableFeatureRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_DisableFeatureRequest, Bucketeer_Feature_DisableFeatureResponse>

  func archiveFeature(
    _ request: Bucketeer_Feature_ArchiveFeatureRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_ArchiveFeatureRequest, Bucketeer_Feature_ArchiveFeatureResponse>

  func deleteFeature(
    _ request: Bucketeer_Feature_DeleteFeatureRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_DeleteFeatureRequest, Bucketeer_Feature_DeleteFeatureResponse>

  func updateFeatureDetails(
    _ request: Bucketeer_Feature_UpdateFeatureDetailsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_UpdateFeatureDetailsRequest, Bucketeer_Feature_UpdateFeatureDetailsResponse>

  func updateFeatureVariations(
    _ request: Bucketeer_Feature_UpdateFeatureVariationsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_UpdateFeatureVariationsRequest, Bucketeer_Feature_UpdateFeatureVariationsResponse>

  func updateFeatureTargeting(
    _ request: Bucketeer_Feature_UpdateFeatureTargetingRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_UpdateFeatureTargetingRequest, Bucketeer_Feature_UpdateFeatureTargetingResponse>

  func cloneFeature(
    _ request: Bucketeer_Feature_CloneFeatureRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_CloneFeatureRequest, Bucketeer_Feature_CloneFeatureResponse>

  func createSegment(
    _ request: Bucketeer_Feature_CreateSegmentRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_CreateSegmentRequest, Bucketeer_Feature_CreateSegmentResponse>

  func getSegment(
    _ request: Bucketeer_Feature_GetSegmentRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_GetSegmentRequest, Bucketeer_Feature_GetSegmentResponse>

  func listSegments(
    _ request: Bucketeer_Feature_ListSegmentsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_ListSegmentsRequest, Bucketeer_Feature_ListSegmentsResponse>

  func deleteSegment(
    _ request: Bucketeer_Feature_DeleteSegmentRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_DeleteSegmentRequest, Bucketeer_Feature_DeleteSegmentResponse>

  func updateSegment(
    _ request: Bucketeer_Feature_UpdateSegmentRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_UpdateSegmentRequest, Bucketeer_Feature_UpdateSegmentResponse>

  func addSegmentUser(
    _ request: Bucketeer_Feature_AddSegmentUserRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_AddSegmentUserRequest, Bucketeer_Feature_AddSegmentUserResponse>

  func deleteSegmentUser(
    _ request: Bucketeer_Feature_DeleteSegmentUserRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_DeleteSegmentUserRequest, Bucketeer_Feature_DeleteSegmentUserResponse>

  func getSegmentUser(
    _ request: Bucketeer_Feature_GetSegmentUserRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_GetSegmentUserRequest, Bucketeer_Feature_GetSegmentUserResponse>

  func listSegmentUsers(
    _ request: Bucketeer_Feature_ListSegmentUsersRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_ListSegmentUsersRequest, Bucketeer_Feature_ListSegmentUsersResponse>

  func bulkUploadSegmentUsers(
    _ request: Bucketeer_Feature_BulkUploadSegmentUsersRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_BulkUploadSegmentUsersRequest, Bucketeer_Feature_BulkUploadSegmentUsersResponse>

  func bulkDownloadSegmentUsers(
    _ request: Bucketeer_Feature_BulkDownloadSegmentUsersRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_BulkDownloadSegmentUsersRequest, Bucketeer_Feature_BulkDownloadSegmentUsersResponse>

  func evaluateOnAllFeatures(
    _ request: Bucketeer_Feature_EvaluateOnAllFeaturesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_EvaluateOnAllFeaturesRequest, Bucketeer_Feature_EvaluateOnAllFeaturesResponse>

  func getUserEvaluations(
    _ request: Bucketeer_Feature_GetUserEvaluationsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_GetUserEvaluationsRequest, Bucketeer_Feature_GetUserEvaluationsResponse>

  func upsertUserEvaluation(
    _ request: Bucketeer_Feature_UpsertUserEvaluationRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bucketeer_Feature_UpsertUserEvaluationRequest, Bucketeer_Feature_UpsertUserEvaluationResponse>

}

extension Bucketeer_Feature_FeatureServiceClientProtocol {

  /// Unary call to SearchFeatures
  ///
  /// - Parameters:
  ///   - request: Request to send to SearchFeatures.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func searchFeatures(
    _ request: Bucketeer_Feature_SearchFeaturesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_SearchFeaturesRequest, Bucketeer_Feature_SearchFeaturesResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/SearchFeatures",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to GetFeature
  ///
  /// - Parameters:
  ///   - request: Request to send to GetFeature.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getFeature(
    _ request: Bucketeer_Feature_GetFeatureRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_GetFeatureRequest, Bucketeer_Feature_GetFeatureResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/GetFeature",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to GetFeatures
  ///
  /// - Parameters:
  ///   - request: Request to send to GetFeatures.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getFeatures(
    _ request: Bucketeer_Feature_GetFeaturesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_GetFeaturesRequest, Bucketeer_Feature_GetFeaturesResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/GetFeatures",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to ListFeatures
  ///
  /// - Parameters:
  ///   - request: Request to send to ListFeatures.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func listFeatures(
    _ request: Bucketeer_Feature_ListFeaturesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_ListFeaturesRequest, Bucketeer_Feature_ListFeaturesResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/ListFeatures",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to ListEnabledFeatures
  ///
  /// - Parameters:
  ///   - request: Request to send to ListEnabledFeatures.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func listEnabledFeatures(
    _ request: Bucketeer_Feature_ListEnabledFeaturesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_ListEnabledFeaturesRequest, Bucketeer_Feature_ListEnabledFeaturesResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/ListEnabledFeatures",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to CreateFeature
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateFeature.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func createFeature(
    _ request: Bucketeer_Feature_CreateFeatureRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_CreateFeatureRequest, Bucketeer_Feature_CreateFeatureResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/CreateFeature",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to EnableFeature
  ///
  /// - Parameters:
  ///   - request: Request to send to EnableFeature.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func enableFeature(
    _ request: Bucketeer_Feature_EnableFeatureRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_EnableFeatureRequest, Bucketeer_Feature_EnableFeatureResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/EnableFeature",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to DisableFeature
  ///
  /// - Parameters:
  ///   - request: Request to send to DisableFeature.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func disableFeature(
    _ request: Bucketeer_Feature_DisableFeatureRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_DisableFeatureRequest, Bucketeer_Feature_DisableFeatureResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/DisableFeature",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to ArchiveFeature
  ///
  /// - Parameters:
  ///   - request: Request to send to ArchiveFeature.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func archiveFeature(
    _ request: Bucketeer_Feature_ArchiveFeatureRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_ArchiveFeatureRequest, Bucketeer_Feature_ArchiveFeatureResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/ArchiveFeature",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to DeleteFeature
  ///
  /// - Parameters:
  ///   - request: Request to send to DeleteFeature.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func deleteFeature(
    _ request: Bucketeer_Feature_DeleteFeatureRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_DeleteFeatureRequest, Bucketeer_Feature_DeleteFeatureResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/DeleteFeature",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to UpdateFeatureDetails
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateFeatureDetails.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func updateFeatureDetails(
    _ request: Bucketeer_Feature_UpdateFeatureDetailsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_UpdateFeatureDetailsRequest, Bucketeer_Feature_UpdateFeatureDetailsResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/UpdateFeatureDetails",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to UpdateFeatureVariations
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateFeatureVariations.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func updateFeatureVariations(
    _ request: Bucketeer_Feature_UpdateFeatureVariationsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_UpdateFeatureVariationsRequest, Bucketeer_Feature_UpdateFeatureVariationsResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/UpdateFeatureVariations",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to UpdateFeatureTargeting
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateFeatureTargeting.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func updateFeatureTargeting(
    _ request: Bucketeer_Feature_UpdateFeatureTargetingRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_UpdateFeatureTargetingRequest, Bucketeer_Feature_UpdateFeatureTargetingResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/UpdateFeatureTargeting",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to CloneFeature
  ///
  /// - Parameters:
  ///   - request: Request to send to CloneFeature.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func cloneFeature(
    _ request: Bucketeer_Feature_CloneFeatureRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_CloneFeatureRequest, Bucketeer_Feature_CloneFeatureResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/CloneFeature",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to CreateSegment
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateSegment.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func createSegment(
    _ request: Bucketeer_Feature_CreateSegmentRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_CreateSegmentRequest, Bucketeer_Feature_CreateSegmentResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/CreateSegment",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to GetSegment
  ///
  /// - Parameters:
  ///   - request: Request to send to GetSegment.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getSegment(
    _ request: Bucketeer_Feature_GetSegmentRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_GetSegmentRequest, Bucketeer_Feature_GetSegmentResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/GetSegment",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to ListSegments
  ///
  /// - Parameters:
  ///   - request: Request to send to ListSegments.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func listSegments(
    _ request: Bucketeer_Feature_ListSegmentsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_ListSegmentsRequest, Bucketeer_Feature_ListSegmentsResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/ListSegments",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to DeleteSegment
  ///
  /// - Parameters:
  ///   - request: Request to send to DeleteSegment.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func deleteSegment(
    _ request: Bucketeer_Feature_DeleteSegmentRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_DeleteSegmentRequest, Bucketeer_Feature_DeleteSegmentResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/DeleteSegment",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to UpdateSegment
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateSegment.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func updateSegment(
    _ request: Bucketeer_Feature_UpdateSegmentRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_UpdateSegmentRequest, Bucketeer_Feature_UpdateSegmentResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/UpdateSegment",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to AddSegmentUser
  ///
  /// - Parameters:
  ///   - request: Request to send to AddSegmentUser.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func addSegmentUser(
    _ request: Bucketeer_Feature_AddSegmentUserRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_AddSegmentUserRequest, Bucketeer_Feature_AddSegmentUserResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/AddSegmentUser",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to DeleteSegmentUser
  ///
  /// - Parameters:
  ///   - request: Request to send to DeleteSegmentUser.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func deleteSegmentUser(
    _ request: Bucketeer_Feature_DeleteSegmentUserRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_DeleteSegmentUserRequest, Bucketeer_Feature_DeleteSegmentUserResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/DeleteSegmentUser",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to GetSegmentUser
  ///
  /// - Parameters:
  ///   - request: Request to send to GetSegmentUser.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getSegmentUser(
    _ request: Bucketeer_Feature_GetSegmentUserRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_GetSegmentUserRequest, Bucketeer_Feature_GetSegmentUserResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/GetSegmentUser",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to ListSegmentUsers
  ///
  /// - Parameters:
  ///   - request: Request to send to ListSegmentUsers.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func listSegmentUsers(
    _ request: Bucketeer_Feature_ListSegmentUsersRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_ListSegmentUsersRequest, Bucketeer_Feature_ListSegmentUsersResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/ListSegmentUsers",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to BulkUploadSegmentUsers
  ///
  /// - Parameters:
  ///   - request: Request to send to BulkUploadSegmentUsers.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func bulkUploadSegmentUsers(
    _ request: Bucketeer_Feature_BulkUploadSegmentUsersRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_BulkUploadSegmentUsersRequest, Bucketeer_Feature_BulkUploadSegmentUsersResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/BulkUploadSegmentUsers",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to BulkDownloadSegmentUsers
  ///
  /// - Parameters:
  ///   - request: Request to send to BulkDownloadSegmentUsers.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func bulkDownloadSegmentUsers(
    _ request: Bucketeer_Feature_BulkDownloadSegmentUsersRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_BulkDownloadSegmentUsersRequest, Bucketeer_Feature_BulkDownloadSegmentUsersResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/BulkDownloadSegmentUsers",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to EvaluateOnAllFeatures
  ///
  /// - Parameters:
  ///   - request: Request to send to EvaluateOnAllFeatures.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func evaluateOnAllFeatures(
    _ request: Bucketeer_Feature_EvaluateOnAllFeaturesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_EvaluateOnAllFeaturesRequest, Bucketeer_Feature_EvaluateOnAllFeaturesResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/EvaluateOnAllFeatures",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to GetUserEvaluations
  ///
  /// - Parameters:
  ///   - request: Request to send to GetUserEvaluations.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getUserEvaluations(
    _ request: Bucketeer_Feature_GetUserEvaluationsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_GetUserEvaluationsRequest, Bucketeer_Feature_GetUserEvaluationsResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/GetUserEvaluations",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to UpsertUserEvaluation
  ///
  /// - Parameters:
  ///   - request: Request to send to UpsertUserEvaluation.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func upsertUserEvaluation(
    _ request: Bucketeer_Feature_UpsertUserEvaluationRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bucketeer_Feature_UpsertUserEvaluationRequest, Bucketeer_Feature_UpsertUserEvaluationResponse> {
    return self.makeUnaryCall(
      path: "/bucketeer.feature.FeatureService/UpsertUserEvaluation",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }
}

internal final class Bucketeer_Feature_FeatureServiceClient: Bucketeer_Feature_FeatureServiceClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions

  /// Creates a client for the bucketeer.feature.FeatureService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  internal init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }
}

